version: '3'
services:
  hk-mysql:
    container_name: hk-mysql
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_DATABASE: root
      MYSQL_ROOT_PASSWORD: 951753qwerty
      MYSQL_ROOT_HOST: '%'
    # ports:
    # - "3306:3306"
    restart: always

  registration-login:
    build: .
    volumes:
    - .:/app
    - ~/.m2:/root/.m2
    working_dir: /app
    ports:
    - 8090:8080
    command: mvn clean spring-boot:run
    depends_on:
    - hk-mysql
