---
version: "3.2"
services:
  web:
    build: .
    ports:
      - "8080:8080"
    restart: "always"
  mysql:
    image: "mysql:8.0"
    container_name: "appsDB"
    restart: "always"
    volumes:
      - ./hotelmanagement_guest.sql:/root/project/hotelmanagement_guest.sql
    environment:
      MYSQL_ROOT_PASSWORD: "super_secret_password"
      MYSQL_USER: "test"
      MYSQL_PASS: "testpass"
volumes:
  hotelmanagement_guest.sql:
